import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { getFooterData } from "./lib/footer.service";
import Footer from "./components/layouts/Footer";
import Navbar from "./components/layouts/NavBar";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "CVM Website",
  description: "Generated by CVM Website",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const footerData = await getFooterData();
  
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Navbar />
        {children}
        <Footer data={footerData}/>
      </body>
    </html>
  );
}
